plugins {
    id 'java-library'
}

group = 'com.maris7'
version = '1.0'

repositories {
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://repo.codemc.io/repository/maven-releases/' }
    maven { url = 'https://repo.codemc.io/repository/maven-snapshots/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.+'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
    compileOnly 'com.zaxxer:HikariCP:7.0.2'
    compileOnly 'org.xerial:sqlite-jdbc:3.53.0.0'
    compileOnly 'com.mysql:mysql-connector-j:9.7.0'
    compileOnly 'com.github.retrooper:packetevents-spigot:2.12.1'
    compileOnly 'com.github.PlaceholderAPI:PlaceholderAPI:2.11.6'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

jar {
    archiveBaseName = 'MarisWorth'
    archiveVersion = ''
}


